import { h, Component } from "preact";

import api from "api.js";

import LoadingIndicator from "ui/LoadingIndicator.jsx";

class TwoFactorInfo extends Component {
	componentWillMount() {
		var that = this;

		this.setState({
			loading: true
		}, function() {
			api.get("auth/2fa/status", {}, function(data) {
				that.setState({
					loading: false,
					enrolled: data.enrolled
				});
			});
		});
	}

	manage2fa() {
		this.props.openModal("twoFactor", {
			enrolled: this.state.enrolled
		});
	}

	render(props, state) {
		if (state.loading) {
			return <div class="twoFactorInfo">
				<h4>Two-factor authentication</h4>
				<p>Two-factor authentication adds an additional layer of protection to your account. Whenever you log in, you'll have to enter a one time password, generated by an app on your phone, to access the account.</p>

				<LoadingIndicator /> Loading, please wait...
			</div>;
		}

		return <div class="twoFactorInfo">
			<h4>Two-factor authentication</h4>
			<p>Two-factor authentication adds an additional layer of protection to your account. Whenever you log in, you'll have to enter a one time password, generated by an app on your phone, to access the account.</p>

			<div>
				It's currently <strong>{state.enrolled ? "enabled" : "disabled"}</strong> on your account.
				<button class={`btn btn-sm btn-${state.enrolled ? "danger" : "primary"}`} onClick={this.manage2fa.bind(this)}>{state.enrolled ? "disable" : "enable"}</button>
			</div>
		</div>;
	}
};

export default TwoFactorInfo;