import "settings/panes/account/AccountPane.styl";

import { h, Component } from "preact";

import SchoolList from "settings/panes/account/SchoolList.jsx";
import TwoFactorInfo from "settings/panes/account/TwoFactorInfo.jsx";

export default class AccountPane extends Component {
	changeBackground() {
		this.props.openModal("background", {});
	}

	changeEmail() {
		this.props.openModal("changeEmail", {});
	}

	changePassword() {
		this.props.openModal("changePassword", {});
	}

	connectAccount() {
		this.props.openModal("enroll", {});
	}

	render(props, state) {
		return <div class="accountPane">
			<div class="accountGroup">
				<div class="profile">
					<h3 class="name">{props.me.name}</h3>
					<h4 class="email">{props.me.email}</h4>
				</div>
				<button class="btn btn-primary" onClick={this.changeEmail.bind(this)}><i class="fa fa-fw fa-envelope" /> Change email</button>
			</div>

			<div class="accountGroup">
				<h4>Background</h4>
				<button class="btn btn-primary" onClick={this.changeBackground.bind(this)}><i class="fa fa-fw fa-picture-o" /> Change background</button>
			</div>

			<div class="accountGroup">
				<h4>Security</h4>

				<h5>Password</h5>
				<button class="btn btn-primary" onClick={this.changePassword.bind(this)}><i class="fa fa-fw fa-key" /> Change password</button>

				<h5>Two-factor authentication</h5>
				<p>Two-factor authentication adds an additional layer of protection to your account. Whenever you log in, you'll have to enter a one time password, generated by an app on your phone, to access the account.</p>
				<TwoFactorInfo openModal={props.openModal} />
			</div>

			<div class="accountGroup schools">
				<h4>Connected school accounts</h4>
				<p>You can connect your school account to MyHomeworkSpace and we'll automatically import your schedule and other information.</p>

				<button class="btn btn-primary" onClick={this.connectAccount.bind(this)}><i class="fa fa-fw fa-link" /> Connect account</button>
				<SchoolList me={props.me} openModal={props.openModal} />
			</div>
		</div>;
	}
};